### ISSUE TITLE
ult-custom-listings Error: Failed to patch \lst@MakeCaption.

### ISSUE THREAD

**Issue by engeir** [egraff/uit-thesis#93] opened 2024-06-24 11:20 UTC
When trying to compile I get the following error

```console
! Package ult-custom-listings Error: Failed to patch \lst@MakeCaption.
```

I am on linux/ubuntu, and it might be that installing the `texlive-full` package fixes the error. However, I only have ~8GB of storage left, so I can't install the full package.

Instead, I have [tinytex](https://github.com/rstudio/tinytex) installed, and `tlmgr install ...` the missing `.sty` files as necessary.

Do you know of a way around the error message above, or is texlive-full needed?

Thanks!

**Comment by egraff** [comment] 2024-06-25 16:10
This is a regression that has already been fixed some months ago. You just need to pull the latest `uit-thesis` (+ `ult-base` submodule) 🙂

Closing as duplicate of #86.

**Closed by egraff** 2024-06-25 16:10 UTC
