### ISSUE TITLE
\begin{document} triggers patch error in ult-custom-listings

### ISSUE THREAD

**Issue by frapzo** [egraff/uit-thesis#96] opened 2024-08-29 11:55 UTC
![Screenshot from 2024-08-29 13-49-07](https://github.com/user-attachments/assets/e7cd38de-9238-4c41-acc1-961db66556ef)

I can't yet see if this has any real impact on how the thesis will look as not much has been added to it yet, but this error happens regardless of which tex file in the template is compiled in Overleaf as long as it contains the line

`\begin{document}`

This error could also potentially be Overleaf specific.

**Comment by egraff** [comment] 2024-09-02 09:24
This is a regression that has already been fixed some months ago. You just need to pull the latest uit-thesis (+ ult-base submodule) 🙂

Closing as duplicate of https://github.com/egraff/uit-thesis/issues/86.

**Closed by egraff** 2024-09-02 09:24 UTC
